version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: all
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: all
        update-types: ["version-update:semver-major"]
