version: '3.8'

services:
  web:
    build:
      context: .
      target: build # Use the build stage for development
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL:-}
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    command: [ "./bin/rails", "server", "-b", "0.0.0.0" ]
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
    driver: local
  node_modules:
    driver: local
