version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=your_secret_key_base_here_change_this_in_production
      - TELEGRAM_USE_WEBHOOKS=true
      # Add TELEGRAM_BOT_TOKEN as needed (should be set via secrets in production)
    volumes:
      - splitmysub_storage:/rails/storage
      - splitmysub_db:/rails/db
    restart: unless-stopped

volumes:
  splitmysub_storage:
    driver: local
  splitmysub_db:
    driver: local
