version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=your_secret_key_base_here_change_this_in_production
    volumes:
      - splitsub_storage:/rails/storage
      - splitsub_db:/rails/db
    restart: unless-stopped

volumes:
  splitsub_storage:
    driver: local
  splitsub_db:
    driver: local
